package shared.constants;

/**
 * Enum representing all possible commands that can be sent between the client and the server.
 */
public enum ProtocolCommands {
    UNKNOWN_COMMAND,
    PARSE_ERROR,
    JOINED,
    READY,
    ENTER,
    ENTER_RESP,
    BROADCAST_REQ,
    BROADCAST_RESP,
    BROADCAST,
    PING,
    PONG,
    PONG_ERROR,
    BYE,
    BYE_RESP,
    HANGUP,
    LEFT,
    CLIENTS_REQ,
    CLIENTS_RESP,
    CLIENTS,
    PRIVATE_REQ,
    PRIVATE_RESP,
    PRIVATE,
    RPS_START_REQ,
    RPS_START_RESP,
    RPS_START,
    RPS_CHOICE_REQ,
    RPS_CHOICE_RESP,
    RPS_END,
    RPS_ERROR,
    TRANSFER_REQ,
    TRANSFER_RESP,
    TRANSFER_ACCEPT,
    TRANSFER_ACCEPT_RESP,
    TRANSFER_REJECT,
    TRANSFER_REJECT_RESP,
    TRANSFER_ACCEPTED,
    TRANSFER_REJECTED,
    TRANSFER_CHECKSUM,
    TRANSFER_FAILED,
    TRANSFER_SUCCESS,
}
